use_frameworks!

platform :ios, '9.0'

target 'MobileExtensionTestbed_Example' do
  pod 'MobileExtensionTestbed', :path => '../'

  target 'MobileExtensionTestbed_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
